/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { FunctionResponseScheduling } from '@google/genai';
import { FunctionCall } from '../state';

/**
 * WhatsApp function calling tools for Evolution API integration.
 * Enables the Gemini Live audio assistant to search, read, send, and manage WhatsApp.
 */
export const whatsappTools: FunctionCall[] = [
  {
    name: 'send_whatsapp_message',
    description: 'Sends a text message to a WhatsApp contact. Use phoneNumber (with country code, e.g., 639916188713) and the message text.',
    parameters: {
      type: 'OBJECT',
      properties: {
        phoneNumber: {
          type: 'STRING',
          description: 'Recipient phone number with country code (e.g., 639916188713).',
        },
        message: {
          type: 'STRING',
          description: 'The text message content to send.',
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
      required: ['phoneNumber', 'message'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'generate_cartesia_voice',
    description: 'Generates audio from text using Cartesia Sonic 3.5 TTS. Returns base64-encoded WAV audio that can be sent via WhatsApp voice message. Supports multiple languages and emotions.',
    parameters: {
      type: 'OBJECT',
      properties: {
        text: {
          type: 'STRING',
          description: 'The text to convert to speech.',
        },
        language: {
          type: 'STRING',
          description: 'Language code (e.g., "en" for English, "tl" for Tagalog, "es" for Spanish). Defaults to "en".',
        },
        emotion: {
          type: 'STRING',
          description: 'Emotion for the voice: "content", "happy", "sad", "angry", "surprised". Defaults to "content".',
        },
        speed: {
          type: 'NUMBER',
          description: 'Speech speed multiplier. 1 is normal. Defaults to 1.',
        },
        volume: {
          type: 'NUMBER',
          description: 'Volume multiplier. 1 is normal. Defaults to 1.',
        },
      },
      required: ['text'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'send_voice_message',
    description: 'Sends a voice/audio message to WhatsApp. Use audioBase64 from generate_cartesia_voice output.',
    parameters: {
      type: 'OBJECT',
      properties: {
        phoneNumber: {
          type: 'STRING',
          description: 'Recipient phone number with country code.',
        },
        audioBase64: {
          type: 'STRING',
          description: 'Base64 encoded audio file (generated by generate_cartesia_voice).',
        },
        caption: {
          type: 'STRING',
          description: 'Optional caption for the voice message.',
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
      required: ['phoneNumber', 'audioBase64'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'search_whatsapp_messages',
    description: 'Searches WhatsApp messages from a specific contact. Returns recent message history.',
    parameters: {
      type: 'OBJECT',
      properties: {
        phoneNumber: {
          type: 'STRING',
          description: 'Phone number of the contact to search (e.g., 639916188713).',
        },
        query: {
          type: 'STRING',
          description: 'Optional search query to filter messages.',
        },
        limit: {
          type: 'INTEGER',
          description: 'Maximum messages to return. Defaults to 20.',
          enum: [5, 10, 20, 50],
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
      required: ['phoneNumber'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'read_whatsapp_chat',
    description: 'Reads recent chat history with a WhatsApp contact. Retrieves conversation thread.',
    parameters: {
      type: 'OBJECT',
      properties: {
        phoneNumber: {
          type: 'STRING',
          description: 'Phone number of the contact (e.g., 639916188713).',
        },
        limit: {
          type: 'INTEGER',
          description: 'Maximum messages to retrieve. Defaults to 30.',
          enum: [10, 20, 30, 50],
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
      required: ['phoneNumber'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'get_whatsapp_status',
    description: 'Checks WhatsApp instance connection status and shows connected phone number and account name.',
    parameters: {
      type: 'OBJECT',
      properties: {
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'get_whatsapp_phonebook',
    description: 'Lists all WhatsApp contacts from your phonebook. Returns names and phone numbers for reference when sending messages.',
    parameters: {
      type: 'OBJECT',
      properties: {
        limit: {
          type: 'INTEGER',
          description: 'Maximum contacts to return. Defaults to 100.',
          enum: [10, 20, 50, 100, 200],
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'get_whatsapp_contacts',
    description: 'Lists WhatsApp contacts (alternative to phonebook). Use when you need contact details.',
    parameters: {
      type: 'OBJECT',
      properties: {
        limit: {
          type: 'INTEGER',
          description: 'Maximum contacts to return. Defaults to 50.',
          enum: [10, 20, 50, 100],
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
  {
    name: 'initiate_whatsapp_call',
    description: 'Initiates a WhatsApp voice or video call to a contact. Use to start a real-time call.',
    parameters: {
      type: 'OBJECT',
      properties: {
        phoneNumber: {
          type: 'STRING',
          description: 'Phone number to call (e.g., 639916188713).',
        },
        callType: {
          type: 'STRING',
          description: 'Type of call: "voice" or "video". Defaults to voice.',
          enum: ['voice', 'video'],
        },
        instanceName: {
          type: 'STRING',
          description: 'Evolution instance name (e.g., beatrice). Defaults to beatrice.',
        },
      },
      required: ['phoneNumber'],
    },
    isEnabled: true,
    scheduling: FunctionResponseScheduling.INTERRUPT,
  },
];
